package uz.com.platform.app.users;

import org.springframework.security.core.GrantedAuthority;

public enum Permission implements GrantedAuthority {

    //    BASIC PERMISSIONS
    CREATE_DB,
    LOGIN_TO_SYSTEM,
    SET_CONFIRM,
    SET_OWN_CONFIRM,

    //    ALL EVENT
    CREATE_ALL_ENTITY,
    UPDATE_ALL_ENTITY,
    DELETE_ALL_ENTITY,
    VIEW_ALL_ENTITY,

    //    OWN
    CREATE_ALL_OWN_DEPARTMENT_ENTITY,
    UPDATE_ALL_OWN_DEPARTMENT_ENTITY,
    DELETE_ALL_OWN_DEPARTMENT_ENTITY,
    VIEW_ALL_OWN_DEPARTMENT_ENTITY,

    //    USERS
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,
    VIEW_USER,

    //    USERS
    CREATE_OWN_DEPARTMENT_USER,
    UPDATE_OWN_DEPARTMENT_USER,
    DELETE_OWN_DEPARTMENT_USER,
    VIEW_OWN_DEPARTMENT_USER,

    //    APPLICATIONS
    CREATE_APPLICATION,
    UPDATE_APPLICATION,
    DELETE_APPLICATION,
    VIEW_APPLICATION,
    VIEW_TYPE_NEW_APPLICATION,
    VIEW_TYPE_CONFIRM_APPLICATION,
    VIEW_TYPE_RESOLUTION_APPLICATION,
    VIEW_TYPE_SEND_TO_ORGANIZATION_APPLICATION,
    VIEW_TYPE_SEND_TO_EXPEDITION_APPLICATION,
    VIEW_TYPE_SEND_TO_CONTROL_APPLICATION,
    VIEW_TYPE_RECEIVE_FROM_ORGANIZATION,

    //    OWN
    CREATE_OWN_DEPARTMENT_APPLICATION,
    UPDATE_OWN_DEPARTMENT_APPLICATION,
    DELETE_OWN_DEPARTMENT_APPLICATION,
    VIEW_OWN_DEPARTMENT_APPLICATION,

    //    RESOLUTIONS
    CREATE_RESOLUTION,
    UPDATE_RESOLUTION,
    DELETE_RESOLUTION,
    VIEW_RESOLUTION,

    //       OWN
    CREATE_OWN_DEPARTMENT_RESOLUTION,
    UPDATE_OWN_DEPARTMENT_RESOLUTION,
    DELETE_OWN_DEPARTMENT_RESOLUTION,
    VIEW_OWN_DEPARTMENT_RESOLUTION,

    //    SENDS
    CREATE_SEND,
    UPDATE_SEND,
    DELETE_SEND,
    VIEW_SEND,

    //       OWN
    CREATE_OWN_DEPARTMENT_SEND,
    UPDATE_OWN_DEPARTMENT_SEND,
    DELETE_OWN_DEPARTMENT_SEND,
    VIEW_OWN_DEPARTMENT_SEND;


    @Override
    public String

    getAuthority() {
        return this.toString();
    }
}
